#ifndef POKEPLATINUM_STRUCT_0202FAA8_SUB1_DECL_H
#define POKEPLATINUM_STRUCT_0202FAA8_SUB1_DECL_H

typedef struct BattleRecordingDataFieldBattleDTO_sub1_t BattleRecordingDataFieldBattleDTO_sub1;

#endif // POKEPLATINUM_STRUCT_0202FAA8_SUB1_DECL_H
